aliases:
  debug:container:
    - cod
  config:edit:
    - cdit
  cron:execute:
    - cre
  database:connect:
    - sqlc
  database:query:
    - sqlq
  debug:database:log:
    - ws
  debug:multisite:
    - msd
  debug:router:
    - rod
  debug:theme:
    - tde
  debug:update:
    - upd
  multisite:new:
    - sn
  router:rebuild:
    - ror
  site:status:
    - st
  user:login:clear:attempts:
    - uslca
  user:login:url:
    - usli
    - uli
  user:password:hash:
    - usph
  user:password:reset:
    - upsr
  views:disable:
    - vdi
  cache:rebuild:
    - cc
  update:execute:
    - updb
  server:
      - rs
