application:
  language: 'en'
  autowire:
    commands:
      forced:
        _completion:
          class: '\Stecman\Component\Symfony\Console\BashCompletion\CompletionCommand'
      name:
        elephpant:
          class: '\Drupal\Console\Core\Command\Exclude\ElephpantCommand'
          arguments: ['@app.root', '@console.renderer', '@console.configuration_manager']
        druplicon:
          class: '\Drupal\Console\Core\Command\Exclude\DrupliconCommand'
          arguments: ['@app.root', '@console.renderer', '@console.configuration_manager']
  commands:
    aliases: ~
    defaults: ~
    mappings: ~
  languages:
    en: 'English'
    es: 'Español'
    ca: 'Català'
    fr: 'Français'
    ko: '한국어'
    hi: 'हिन्दी'
    hu: 'Magyar'
    id: 'Bahasa Indonesia'
    ja: '日本語'
    mr: 'मराठी'
    pa: 'ਪੰਜਾਬੀ'
    pt-br: 'Português'
    ro: 'Romanian'
    ru: 'pусский язык'
    tl: 'Tagalog'
    vn: 'Tiếng Việt'
    zh-hans: '简体中文'
    zh-hant: '繁體中文'
