requirements:
  php:
    required: 5.5.9
  configurations:
    required:
      - date.timezone: 'America/Tijuana'
      - memory_limit: 1024M
    recomended: {}
  extensions:
    required:
      - date
      - dom
      - filter
      - gd
      - hash
      - json
      - pcre
      - pdo
      - session
      - SimpleXML
      - SPL
      - tokenizer
      - xml
      - curl
    recommended: {}
