# How to use
# quick:start --directory=/path/to/drupal-project/
# quick:start --directory=/path/to/drupal-project/ --profile=minimal
# quick:start --repository=weknowinc/drupal-project --directory=/path/to/drupal-project/ --profile=standard
command:
  name: quick:start
  description: 'Download, install and serve a new Drupal project'
vars:
  repository:
    - weknowinc/drupal-project
    - drupal-composer/drupal-project:8.x-dev
    - acquia/lightning-project
    - acquia/reservoir-project
  profile: standard
commands:
  # Create Drupal project using DrupalComposer
  - command: exec
    arguments:
      bin: composer create-project {{repository}} {{directory}} --prefer-dist --no-progress --no-interaction
  # Install Drupal
  - command: exec
    arguments:
      bin: drupal site:install {{profile}} --root={{directory}} --db-type="sqlite" --no-interaction
  # Start PHP built-in server
  - command: exec
    arguments:
      bin: drupal server --root={{directory}}
